version: 2
jobs:
  build:

    working_directory: ~/profit-calc

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          key: profit-calc-{{ checksum "pom.xml" }}

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: profit-calc-{{ checksum "pom.xml" }}

       - add_ssh_keys:
          fingerprints:
            - "88:4e:fc:e0:9b:32:49:57:c5:a5:62:46:4a:63:e1:d6"

      - deploy:
            name: Deploy Website to gh-pages
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git config --global user.email "4-bar-killa@web.de"
                git config --global user.name "mszalbach"
                ./myarn deploy
              fi
